export default [
  { id: 1, name: "Milk", active: true },
  { id: 2, name: "Bread", active: false },
  { id: 3, name: "Eggs", active: true },
  { id: 4, name: "Apples", active: true },
  { id: 5, name: "Cheese", active: false },
  { id: 6, name: "Butter", active: true },
  { id: 7, name: "Yogurt", active: false },
  { id: 8, name: "Bananas", active: true },
  { id: 9, name: "Chicken Breast", active: true },
  { id: 10, name: "Rice", active: false },
  { id: 11, name: "Pasta", active: true },
  { id: 12, name: "Tomatoes", active: true },
  { id: 13, name: "Potatoes", active: false },
  { id: 14, name: "Onions", active: true },
  { id: 15, name: "Carrots", active: false },
  { id: 16, name: "Lettuce", active: true },
  { id: 17, name: "Cereal", active: true },
  { id: 18, name: "Orange Juice", active: false },
  { id: 19, name: "Coffee", active: true },
  { id: 20, name: "Tea", active: false },
  { id: 21, name: "Sugar", active: true },
  { id: 22, name: "Salt", active: true },
  { id: 23, name: "Pepper", active: false },
  { id: 24, name: "Ketchup", active: true },
  { id: 25, name: "Mustard", active: false },
  { id: 26, name: "Cooking Oil", active: true },
  { id: 27, name: "Flour", active: false },
  { id: 28, name: "Baking Powder", active: true },
  { id: 29, name: "Chocolate", active: true },
  { id: 30, name: "Cookies", active: false },
  { id: 31, name: "Chips", active: true },
  { id: 32, name: "Frozen Pizza", active: false },
  { id: 33, name: "Ice Cream", active: true },
  { id: 34, name: "Water Bottles", active: true },
  { id: 35, name: "Soda", active: false },
  { id: 36, name: "Beer", active: true },
  { id: 37, name: "Wine", active: false },
  { id: 38, name: "Toilet Paper", active: true },
  { id: 39, name: "Paper Towels", active: false },
  { id: 40, name: "Dish Soap", active: true },
];
